export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST'
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED'
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR'

export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED'
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR'

export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS'
export const REMOVE_TASK_ERROR = 'REMOVE_TASK_ERROR'

export const LIST_TASK_SUCCESS = 'LIST_TASK_SUCCESS'
export const LIST_TASK_ERROR = 'LIST_TASK_ERROR'

export const TASK_SUCCESS = 'TASK_SUCCESS'
export const TASK_ERROR = 'TASK_ERROR'
